# Generated by Django 3.2.7 on 2021-09-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('birth_certificate', models.FileField(upload_to='images')),
                ('national_id_file', models.FileField(upload_to='images')),
                ('school_name', models.CharField(max_length=200)),
                ('school_address', models.CharField(max_length=100)),
                ('expected_year_of_completion', models.DateField(default=None)),
                ('reasons_for_sponsorship', models.TextField(default=False)),
                ('recommendation_letter', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorName', models.CharField(max_length=200)),
                ('SponsorEmail', models.EmailField(default=None, max_length=254, unique=True)),
                ('country', models.CharField(max_length=200)),
                ('sponsoredSchool', models.CharField(max_length=200)),
                ('type_of_sponsorship', models.TextField(default=None)),
            ],
        ),
    ]
