# Generated by Django 3.2.7 on 2021-10-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='country',
            new_name='country_of_origin',
        ),
    ]
