# Generated by Django 3.2.7 on 2021-09-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0004_rename_person_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reasons_for_sponsorship',
            field=models.TextField(),
        ),
    ]
