# Generated by Django 3.2.7 on 2021-10-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0004_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_sponsor',
            field=models.BooleanField(default=True),
        ),
    ]
