# Generated by Django 3.2.7 on 2021-09-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0005_alter_student_reasons_for_sponsorship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='SponsorEmail',
        ),
    ]
